import { ChakraProvider,Container } from "@chakra-ui/react"
import theme from "../theme"

import Head from 'next/head'
import { AppProps } from 'next/app'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Container height="100%">
    <Head>
    <title>News-Page</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <ChakraProvider theme={theme}>
      <Component {...pageProps} />
    </ChakraProvider>
    </Container>
  )
}
export default MyApp